### PR TITLE
fix: set custom-script timezone in `Asia/Shanghai`

### PR DESCRIPTION
**Pull request by chengjoey**
## Description
set custom-script timezone in `Asia/Shanghai`

[erda issue link](https://erda.cloud/erda/dop/projects/387/ticket?id=347609&iterationID=-1&type=TICKET)

## Checklist

 - [ ] I made sure to check the compatibility of the erda version statemented in the action's spec.yml.
 - [ ] My change is adequately tested.

### CODE REVIEW

**Comment by sfwn** [comment]
Also set through action-agent.

**Comment by chengjoey** [comment]
image
image

**Comment by chengjoey** [comment]
> Also set through action-agent.

added

**Review by sfwn — APPROVED** [review]

**Pull request merged**
